import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notokr = Noto_Sans_KR({
  // subsets: [""],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: false
});

export const metadata = {
  title: "Typing Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notokr.className}>{children}</body>
    </html>
  );
}
